version: '3.9'

services:
  web:
    container_name: cotacoes
    build:
      context: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/app
    ports:
    - "8000:8000"
    env_file:
    - .env
    depends_on:
    - postgres

  postgres:
    container_name: postgres
    image: postgres:13.8
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
    - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
