# Generated by Django 4.2.3 on 2023-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("moeda", models.CharField(max_length=30)),
                ("sigla", models.CharField(max_length=3)),
                ("valor", models.FloatField(blank=True, null=True)),
                ("data", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Cotação",
                "verbose_name_plural": "Cotações",
            },
        ),
    ]
